name: SysY Compiler CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Create build directory
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: Style check
      run: make -C build check_format
    - name: Build
      run: make -C build -j$(nproc)
    - name: Test ir
      run: make -C build check_sysyc_ir_opt ARGS=-j$(nproc)
    - name: Test asm
      run: make -C build check_sysyc_asm_opt ARGS=-j$(nproc)
